FROM bitnami/spark:3.5.5

USER root


RUN apt-get clean  && \
    apt-get update && \
    apt-get install -y --no-install-recommends python3-pip

COPY requirements.txt /requirements.txt
RUN pip3 install -r /requirements.txt