/**
 * Automatically generated types for motia
 * Do NOT edit this file manually.
 * 
 * Consider adding this file to .prettierignore and eslint ignore.
 */
import { EventHandler, ApiRouteHandler, ApiResponse, MotiaStream, CronHandler } from 'motia'

declare module 'motia' {
  interface FlowContextStateStreams {
    
  }

  interface Handlers {
    'api-process-files': ApiRouteHandler<{ fileUri: string }, ApiResponse<200, { message: string }>, { topic: 'spark.process.csv'; data: { fileUri: string } }>
    'spark.process.csv': EventHandler<{ fileUri: string }, never>
  }
}