/**
 * Automatically generated types for motia
 * Do NOT edit this file manually.
 * 
 * Consider adding this file to .prettierignore and eslint ignore.
 */
import { EventHandler, ApiRouteHandler, ApiResponse, MotiaStream, CronHandler } from 'motia'

declare module 'motia' {
  interface FlowContextStateStreams {
    
  }

  interface Handlers {
    'spark-analyze': ApiRouteHandler<{ type: 'employees' | 'sales' | 'generic' | 'sql'; csvPath: string; analysisType?: string; sqlQuery?: string; sparkUrl?: string; appName?: string; maxRows?: number; tableName?: string }, ApiResponse<202, { message: string; analysisId: string; type: string; status: string }> | ApiResponse<400, { error: string }> | ApiResponse<500, { error: string }>, { topic: 'spark.employees.analyze'; data: { analysisType?: 'salary_by_department' | 'experience_distribution' | 'department_summary' | 'salary_statistics' | 'all'; csvPath: string; sparkUrl?: string; appName?: string } } | { topic: 'spark.sales.analyze'; data: { analysisType?: 'revenue_by_region' | 'monthly_trends' | 'product_performance' | 'sales_rep_analysis' | 'all'; csvPath: string; sparkUrl?: string; appName?: string } } | { topic: 'spark.generic.analyze'; data: { csvPath: string; analysisType?: 'profile' | 'sample' | 'schema' | 'summary' | 'custom_sql'; customSql?: string; sampleSize?: number; sparkUrl?: string; appName?: string; tableName?: string } } | { topic: 'spark.sql.execute'; data: { csvPath: string; sqlQuery: string; sparkUrl?: string; appName?: string; maxRows?: number; tableName?: string } }>
    'api-process-files': ApiRouteHandler<{ fileUri: string }, ApiResponse<200, { message: string }>, { topic: 'spark.process.csv'; data: { fileUri: string } }>
    'spark.sql.execute': EventHandler<{ csvPath: string; sqlQuery: string; sparkUrl?: string; appName?: string; maxRows?: number; tableName?: string }, never>
    'spark.process.csv': EventHandler<{ fileUri: string }, never>
    'spark.sales.analyze': EventHandler<{ analysisType?: 'revenue_by_region' | 'monthly_trends' | 'product_performance' | 'sales_rep_analysis' | 'all'; csvPath: string; sparkUrl?: string; appName?: string }, never>
    'spark.generic.analyze': EventHandler<{ csvPath: string; analysisType?: 'profile' | 'sample' | 'schema' | 'summary' | 'custom_sql'; customSql?: string; sampleSize?: number; sparkUrl?: string; appName?: string; tableName?: string }, never>
    'spark.employees.analyze': EventHandler<{ analysisType?: 'salary_by_department' | 'experience_distribution' | 'department_summary' | 'salary_statistics' | 'all'; csvPath: string; sparkUrl?: string; appName?: string }, never>
  }
}